---
ID: "f5da1cea-123f-4900-8974-afab755551fd"
Parent: "98127972-d381-4dc7-8e3c-7233372eac24"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Sites/Ignition/Components/CallToAction/CallToActionIconSelector/Parameters
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160608T003447Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
