---
ID: "479d450b-80a7-4d5c-b290-bb7cf804e26a"
Parent: "fddb71b7-bf9f-4bee-861d-c37b29cd5188"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Ignition/Components/Product/Product Summary
DB: master
SharedFields:
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Sites/Ignition/Components/Product/ProductSummary
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: ./Assets
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: "<image mediaid=\"{A62E20F9-8E14-46B2-8964-7E54D8FEAF91}\" />"
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: ProductSummary
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Product
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160822T201100Z
