---
ID: "fddb71b7-bf9f-4bee-861d-c37b29cd5188"
Parent: "ef987e71-c8cf-471e-b08a-2c6febd03c2d"
Template: "7ee0975b-0698-493e-b3a2-0b2ef33d0522"
Path: /sitecore/layout/Renderings/Ignition/Components/Product
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160822T200225Z
