---
ID: "6d6d69bf-992b-4be5-8bda-3aef57886898"
Parent: "1195ece2-b3d8-4211-8e34-c9beb64e09af"
Template: "ab154d3d-1126-4ab4-ac21-8b86e6bd70ea"
Path: /sitecore/system/Modules/PowerShell/Script Library/Ignition/Event Handlers/Roles/Rolesadded/Remote
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160727T142034Z
