---
ID: "b2c57d97-7ae2-4b5c-a4c8-00de74f21569"
Parent: "591dcb0f-6ef6-4a17-8ece-2c7fb1b95953"
Template: "ab154d3d-1126-4ab4-ac21-8b86e6bd70ea"
Path: /sitecore/system/Modules/PowerShell/Script Library/Ignition/Event Handlers/Roles/Rolesremoved/Remote
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160727T142035Z
