---
ID: "6999b5fc-9191-464d-a6d4-1740ea9a9542"
Parent: "5a16438d-19be-4b45-a02c-143f8654d60e"
Template: "ab154d3d-1126-4ab4-ac21-8b86e6bd70ea"
Path: /sitecore/system/Modules/PowerShell/Script Library/Ignition/Content Editor/Ribbon/Security
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160727T142012Z
