---
ID: "9b343d30-85af-45a0-98d9-b6ae1e114ce1"
Parent: "f2f35aa9-485b-4f96-96f5-6cf6fbf79c7a"
Template: "ab154d3d-1126-4ab4-ac21-8b86e6bd70ea"
Path: /sitecore/system/Modules/PowerShell/Script Library/Ignition/Event Handlers/Roles/Usersremoved/Remote
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160727T142036Z
