---
ID: "38030f5e-ea8a-48ec-905b-667dde5206ab"
Parent: "4dcc294f-d5ec-4607-917a-e4a3b80ec624"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Ignition/Settings/StringSetting/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150512T233757Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\jon
